reload_zones:
  target:
    entity:
      integration: "polygonal_zones"

replace_all_zones:
  target:
    entity:
      integration: "polygonal_zones"

  fields:
    zone:
      required: true
      selector:
        text:
          multiline: true

add_new_zone:
  target:
    entity:
      integration: "polygonal_zones"
  fields:
    zone:
      required: true
      selector:
        text:
          multiline: true

edit_zone:
  target:
    entity:
      integration: "polygonal_zones"

  fields:
    zone_name:
      example: "Shopping mall"
      required: true
      selector:
        text:

    zone:
      required: true
      selector:
        text:
          multiline: true

delete_zone:
  target:
    entity:
      integration: polygonal_zones

  fields:
    zone_name:
      example: "Shopping mall"
      required: true
      selector:
        text: {}
